title: giuppep
email: giuseppe@papallo.it
description: Giuseppe Papallo's personal website
baseurl: ""
url: "https://giuppep.github.io"
github_username:  giuppep

# Build settings
plugins:
  - jekyll-seo-tag
#   - jekyll-feed
sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
